name: update

on:
  schedule:
    - cron: '13,43 * * * *'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - run: cd maint && go run main.go > ../rakudo-releases.v1.csv.new
      - run: bash maint/update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
