name: update

# on:
#   schedule:
#     - cron: '13 1 * * *'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-go@v4
        with:
          go-version-file: maint/go.mod
      - run: cd maint && go run main.go > ../rakudo-releases.v1.csv.new
      - run: bash maint/update.sh rakudo-releases.v1.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
